#ifndef __COMMON_H__
#define __COMMON_H__

// These defined values will be generated by a code generating module
// The ideal block sizes chosen by an automated test suite
// The cell size defined by the input

#define HORIZONTAL_K_BLOCKSIZEX 128	//96
#define HORIZONTAL_K_BLOCKSIZEY 1		//2

#define VERTICAL_K_BLOCKSIZEX 32	//16 //32
#define VERTICAL_K_BLOCKSIZEY 16	//24 //12

#define HORIZONTAL_K_BLOCKSIZE (HORIZONTAL_K_BLOCKSIZEX*HORIZONTAL_K_BLOCKSIZEY)//128 //192
#define VERTICAL_K_BLOCKSIZE (VERTICAL_K_BLOCKSIZEX*VERTICAL_K_BLOCKSIZEY)//512 //384

#include "cuda.h"
#include "cuda_runtime.h"
#include "cuda_runtime_api.h"
#include "device_launch_parameters.h"
#include "Timer.h"

#include "params.h"

#endif //-Xptxas -dlcm=cg 